# Generated by Django 4.1.3 on 2022-11-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isSpam',
            field=models.CharField(max_length=10),
        ),
    ]
